# Generated by Django 4.0.1 on 2022-03-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_roles_empleados_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='tipoRol',
            field=models.CharField(choices=[('admin', 'admin'), ('empleado', 'empleado')], db_column='tipoRol', max_length=8),
        ),
    ]
