# Generated by Django 4.0.1 on 2022-03-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_alter_roles_tiporol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='tipoRol',
            field=models.CharField(db_column='tipoRol', max_length=8),
        ),
    ]
