# Generated by Django 4.0.1 on 2022-03-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_alter_roles_tiporol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='adminApp.roles'),
        ),
    ]
