# Generated by Django 4.0.1 on 2022-02-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plazas',
            fields=[
                ('id_plaza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'plazas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('tiporol', models.CharField(db_column='tipoRol', max_length=8)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('appaterno', models.CharField(db_column='apPaterno', max_length=30)),
                ('apmaterno', models.CharField(db_column='apMaterno', max_length=30)),
                ('fnaciemiento', models.DateField(db_column='fNaciemiento')),
                ('user', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
