# Generated by Django 4.0.1 on 2022-02-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioManager',
        ),
    ]
