# Generated by Django 4.0.1 on 2022-03-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_delete_usuariomanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
