# Generated by Django 4.0.1 on 2022-03-19 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessiones',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('key_session', models.CharField(max_length=30)),
                ('key_expire', models.DateField()),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
