# Generated by Django 4.0.1 on 2022-03-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_sessiones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiones',
            options={'managed': False},
        ),
    ]
