# Generated by Django 4.0.1 on 2022-02-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecliente', models.CharField(db_column='nombreCliente', max_length=30)),
                ('cantidadproducto', models.IntegerField(db_column='cantidadProducto')),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(db_column='nombreProducto', max_length=30, unique=True)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fventa', models.DateTimeField(auto_now=True, db_column='fVenta')),
                ('valortotal', models.FloatField(db_column='valorTotal')),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
    ]
