# Generated by Django 4.0.1 on 2022-02-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plazaEmpleadoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'managed': True},
        ),
    ]
