# Generated by Django 4.0.1 on 2022-03-02 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plazaEmpleadoApp', '0003_ventas_id_pedido_ventas_id_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPlaza',
            fields=[
                ('id_productosPlaza', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadProductoPlaza', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ProductoPlaza',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id_producto',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fventa',
            field=models.DateField(auto_now=True, db_column='fVenta'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_productosPlaza',
            field=models.ForeignKey(blank=True, db_column='id_productosPlaza', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plazaEmpleadoApp.productoplaza'),
        ),
    ]
