# Generated by Django 4.0.1 on 2022-03-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plazaEmpleadoApp', '0005_productosplaza_alter_ventas_id_productosplaza_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productosplaza',
            table='ProductosPlaza',
        ),
    ]
