# Generated by Django 4.0.1 on 2022-03-02 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plazaEmpleadoApp', '0006_alter_productosplaza_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='id_productosPlaza',
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plazaEmpleadoApp.productos'),
        ),
        migrations.DeleteModel(
            name='ProductosPlaza',
        ),
    ]
