# Generated by Django 4.0.1 on 2022-03-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plazaEmpleadoApp', '0007_remove_ventas_id_productosplaza_ventas_id_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'managed': True},
        ),
    ]
