# Generated by Django 4.0.1 on 2022-03-02 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_delete_usuariomanager'),
        ('plazaEmpleadoApp', '0008_alter_pedidos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id_abono', models.AutoField(primary_key=True, serialize=False)),
                ('valorAbono', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'db_table': 'abonos',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='pedidos',
            name='descripcionpedido',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_plaza',
            field=models.ForeignKey(blank=True, db_column='id_plaza', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userApp.plazas'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default='', max_digits=30),
            preserve_default=False,
        ),
    ]
