# Generated by Django 4.0.1 on 2022-03-02 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_delete_usuariomanager'),
        ('plazaEmpleadoApp', '0009_abonos_pedidos_descripcionpedido_pedidos_id_plaza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosPlaza',
            fields=[
                ('id_productoPlaza', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadproducto', models.IntegerField(max_length=30)),
                ('id_plaza', models.ForeignKey(blank=True, db_column='id_plaza', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userApp.plazas')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plazaEmpleadoApp.productos')),
            ],
        ),
    ]
