# Generated by Django 4.0.1 on 2022-03-02 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plazaEmpleadoApp', '0010_productosplaza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productosplaza',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_productoPlaza',
            field=models.ForeignKey(blank=True, db_column='id_productoPlaza', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plazaEmpleadoApp.productosplaza'),
        ),
    ]
