# Generated by Django 4.0.1 on 2022-03-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plazaEmpleadoApp', '0011_alter_productosplaza_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productosplaza',
            table='productosplaza',
        ),
    ]
