# Generated by Django 4.0.1 on 2022-03-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazaEmpleadoApp', '0014_alter_pedidos_id_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='estadoPago',
            field=models.BooleanField(default=False),
        ),
    ]
